In [1]:
import pandas as pd

In [2]:
cus_df = pd.read_csv("Raw Data\\blinkit_customers.csv")
ord_df = pd.read_csv("Raw Data\\blinkit_orders.csv")
ord_item_df = pd.read_csv("Raw Data\\blinkit_order_items.csv")
prod_df = pd.read_csv('Raw Data\\blinkit_products.csv')
feedback_df = pd.read_csv("Raw Data\\blinkit_customer_feedback.csv")
delivery_df = pd.read_csv("Raw Data\\blinkit_delivery_performance.csv")
inventory_df = pd.read_csv("Raw Data\\blinkit_inventory.csv")
inventory_new_df = pd.read_csv("Raw Data\\blinkit_inventoryNew.csv")
marketing_df = pd.read_csv("Raw Data\\blinkit_marketing_performance.csv")
category_icon_df = pd.read_excel("Raw Data\\Category_Icons.xlsx")
rating_icon_df = pd.read_excel("Raw Data\\Rating_Icon.xlsx")

In [3]:
datasets = {
    "Customers": cus_df,
    "Orders": ord_df,
    "Order Items": ord_item_df,
    "Products": prod_df,
    "Feedback": feedback_df,
    "Delivery": delivery_df,
    "Inventory": inventory_df,
    "Inventory New": inventory_new_df,
    "Marketing": marketing_df,
    "Category Icon": category_icon_df,
    "Rating Icon": rating_icon_df
}

for name, df in datasets.items():
    print(f"\n{'='*50}")
    print(name)
    print(df.shape)
    print(df.info())
    print(df.isnull().sum())
    print("Duplicates:", df.duplicated().sum())

==================================================
Customers
(2500, 11)
<class 'pandas.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        2500 non-null   int64
 1   customer_name      2500 non-null   str
 2   email              2500 non-null   str
 3   phone              2500 non-null   int64
 4   address            2500 non-null   str
 5   area               2500 non-null   str
 6   pincode            2500 non-null   int64
 7   registration_date  2500 non-null   str
 8   customer_segment   2500 non-null   str
 9   total_orders       2500 non-null   int64
 10  avg_order_value    2500 non-null   float64
dtypes: float64(1), int64(4), str(6)
memory usage: 215.0 KB
None
customer_id          0
customer_name        0
email                0
phone                0
address              0
area                 0
pincode              0
registration_date    0
customer_segment     0
total_orders         0
avg_order_value      0
dtype: int64
Duplicates: 0

==================================================
Orders
(5000, 10)
<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   order_id                5000 non-null   int64
 1   customer_id             5000 non-null   int64
 2   order_date              5000 non-null   str
 3   promised_delivery_time  5000 non-null   str
 4   actual_delivery_time    5000 non-null   str
 5   delivery_status         5000 non-null   str
 6   order_total             5000 non-null   float64
 7   payment_method          5000 non-null   str
 8   delivery_partner_id     5000 non-null   int64
 9   store_id                5000 non-null   int64
dtypes: float64(1), int64(4), str(5)
memory usage: 390.8 KB
None
order_id                  0
customer_id               0
order_date                0
promised_delivery_time    0
actual_delivery_time      0
delivery_status           0
order_total               0
payment_method            0
delivery_partner_id       0
store_id                  0
dtype: int64
Duplicates: 0

==================================================
Order Items
(5000, 4)
<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    5000 non-null   int64
 1   product_id  5000 non-null   int64
 2   quantity    5000 non-null   int64
 3   unit_price  5000 non-null   float64
dtypes: float64(1), int64(3)
memory usage: 156.4 KB
None
order_id      0
product_id    0
quantity      0
unit_price    0
dtype: int64
Duplicates: 0

==================================================
Products
(268, 10)
<class 'pandas.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         268 non-null    int64
 1   product_name       268 non-null    str
 2   category           268 non-null    str
 3   brand              268 non-null    str
 4   price              268 non-null    float64
 5   mrp                268 non-null    float64
 6   margin_percentage  268 non-null    float64
 7   shelf_life_days    268 non-null    int64
 8   min_stock_level    268 non-null    int64
 9   max_stock_level    268 non-null    int64
dtypes: float64(3), int64(4), str(3)
memory usage: 21.1 KB
None
product_id           0
product_name         0
category             0
brand                0
price                0
mrp                  0
margin_percentage    0
shelf_life_days      0
min_stock_level      0
max_stock_level      0
dtype: int64
Duplicates: 0

==================================================
Feedback
(5000, 8)
<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   feedback_id        5000 non-null   int64
 1   order_id           5000 non-null   int64
 2   customer_id        5000 non-null   int64
 3   rating             5000 non-null   int64
 4   feedback_text      5000 non-null   str
 5   feedback_category  5000 non-null   str
 6   sentiment          5000 non-null   str
 7   feedback_date      5000 non-null   str
dtypes: int64(4), str(4)
memory usage: 312.6 KB
None
feedback_id          0
order_id             0
customer_id          0
rating               0
feedback_text        0
feedback_category    0
sentiment            0
feedback_date        0
dtype: int64
Duplicates: 0

==================================================
Delivery
(5000, 8)
<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               5000 non-null   int64
 1   delivery_partner_id    5000 non-null   int64
 2   promised_time          5000 non-null   str
 3   actual_time            5000 non-null   str
 4   delivery_time_minutes  5000 non-null   float64
 5   distance_km            5000 non-null   float64
 6   delivery_status        5000 non-null   str
 7   reasons_if_delayed     3098 non-null   str
dtypes: float64(2), int64(2), str(4)
memory usage: 312.6 KB
None
order_id                    0
delivery_partner_id         0
promised_time               0
actual_time                 0
delivery_time_minutes       0
distance_km                 0
delivery_status             0
reasons_if_delayed       1902
dtype: int64
Duplicates: 0

==================================================
Inventory
(75172, 4)
<class 'pandas.DataFrame'>
RangeIndex: 75172 entries, 0 to 75171
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_id      75172 non-null  int64
 1   date            75172 non-null  str
 2   stock_received  75172 non-null  int64
 3   damaged_stock   75172 non-null  int64
dtypes: int64(3), str(1)
memory usage: 2.3 MB
None
product_id        0
date              0
stock_received    0
damaged_stock     0
dtype: int64
Duplicates: 0

==================================================
Inventory New
(18105, 4)
<class 'pandas.DataFrame'>
RangeIndex: 18105 entries, 0 to 18104
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_id      18105 non-null  int64
 1   date            18105 non-null  str
 2   stock_received  18105 non-null  int64
 3   damaged_stock   18105 non-null  int64
dtypes: int64(3), str(1)
memory usage: 565.9 KB
None
product_id        0
date              0
stock_received    0
damaged_stock     0
dtype: int64
Duplicates: 7359

==================================================
Marketing
(5400, 11)
<class 'pandas.DataFrame'>
RangeIndex: 5400 entries, 0 to 5399
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   campaign_id        5400 non-null   int64
 1   campaign_name      5400 non-null   str
 2   date               5400 non-null   str
 3   target_audience    5400 non-null   str
 4   channel            5400 non-null   str
 5   impressions        5400 non-null   int64
 6   clicks             5400 non-null   int64
 7   conversions        5400 non-null   int64
 8   spend              5400 non-null   float64
 9   revenue_generated  5400 non-null   float64
 10  roas               5400 non-null   float64
dtypes: float64(3), int64(4), str(4)
memory usage: 464.2 KB
None
campaign_id          0
campaign_name        0
date                 0
target_audience      0
channel              0
impressions          0
clicks               0
conversions          0
spend                0
revenue_generated    0
roas                 0
dtype: int64
Duplicates: 0

==================================================
Category Icon
(11, 2)
<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   category  11 non-null     str
 1   Img       11 non-null     str
dtypes: str(2)
memory usage: 308.0 bytes
None
category    0
Img         0
dtype: int64
Duplicates: 0

==================================================
Rating Icon
(5, 3)
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Rating  5 non-null      int64
 1   Emoji   5 non-null      str
 2   Star    5 non-null      str
dtypes: int64(1), str(2)
memory usage: 252.0 bytes
None
Rating    0
Emoji     0
Star      0
dtype: int64
Duplicates: 0

In [4]:
for name, df in datasets.items():
    print(f"\n{name}")
    print(df.columns.tolist())

Customers
['customer_id', 'customer_name', 'email', 'phone', 'address', 'area', 'pincode', 'registration_date', 'customer_segment', 'total_orders', 'avg_order_value']

Orders
['order_id', 'customer_id', 'order_date', 'promised_delivery_time', 'actual_delivery_time', 'delivery_status', 'order_total', 'payment_method', 'delivery_partner_id', 'store_id']

Order Items
['order_id', 'product_id', 'quantity', 'unit_price']

Products
['product_id', 'product_name', 'category', 'brand', 'price', 'mrp', 'margin_percentage', 'shelf_life_days', 'min_stock_level', 'max_stock_level']

Feedback
['feedback_id', 'order_id', 'customer_id', 'rating', 'feedback_text', 'feedback_category', 'sentiment', 'feedback_date']

Delivery
['order_id', 'delivery_partner_id', 'promised_time', 'actual_time', 'delivery_time_minutes', 'distance_km', 'delivery_status', 'reasons_if_delayed']

Inventory
['product_id', 'date', 'stock_received', 'damaged_stock']

Inventory New
['product_id', 'date', 'stock_received', 'damaged_stock']

Marketing
['campaign_id', 'campaign_name', 'date', 'target_audience', 'channel', 'impressions', 'clicks', 'conversions', 'spend', 'revenue_generated', 'roas']

Category Icon
['category', 'Img']

Rating Icon
['Rating', 'Emoji', 'Star']

In [5]:
ord_df['order_date'] = pd.to_datetime(ord_df['order_date'])

In [6]:
cus_df['customer_id'].nunique()

2500

In [7]:
cus_df.head(n=4)

,customer_id,customer_name,email,phone,address,area,pincode,registration_date,customer_segment,total_orders,avg_order_value
0,97475543,Niharika Nagi,ektataneja@example.org,912987579691,"23, Nayar Path, Bihar Sharif-154625",Udupi,321865,2023-05-13,Premium,13,451.92
1,22077605,Megha Sachar,vedant45@example.com,915123179717,"51/302, Buch Chowk\nSrinagar-570271",Aligarh,149394,2024-06-18,Inactive,4,825.48
2,47822591,Hema Bahri,samiazaan@example.com,910034076149,"941\nAnne Street, Darbhanga 186125",Begusarai,621411,2024-09-25,Regular,17,1969.81
3,79726146,Zaitra Vig,ishanvi87@example.org,916264232390,"43/94, Ghosh, Alappuzha 635655",Kozhikode,826054,2023-10-04,New,4,220.09

In [8]:
cus_df[['customer_id', 'customer_name', 'email', 'phone', 'address', 'area',
       'pincode', 'registration_date', 'customer_segment', 'total_orders',
       'avg_order_value']].isnull().sum()

customer_id          0
customer_name        0
email                0
phone                0
address              0
area                 0
pincode              0
registration_date    0
customer_segment     0
total_orders         0
avg_order_value      0
dtype: int64

In [9]:
cus_df[['customer_id', 'customer_name', 'email', 'phone', 'address', 'area',
       'pincode', 'registration_date', 'customer_segment', 'total_orders',
       'avg_order_value']].nunique()

customer_id          2500
customer_name        2491
email                2496
phone                2500
address              2500
area                  316
pincode              2494
registration_date     589
customer_segment        4
total_orders           20
avg_order_value      2487
dtype: int64

In [10]:
ord_df['order_id'].nunique()

5000

In [11]:
ord_df.head()

,order_id,customer_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id
0,1961864118,30065862,2024-07-17 08:34:01,2024-07-17 08:52:01,2024-07-17 08:47:01,On Time,3197.07,Cash,63230,4771
1,1549769649,9573071,2024-05-28 13:14:29,2024-05-28 13:25:29,2024-05-28 13:27:29,On Time,976.55,Cash,14983,7534
2,9185164487,45477575,2024-09-23 13:07:12,2024-09-23 13:25:12,2024-09-23 13:29:12,On Time,839.05,UPI,39859,9886
3,9644738826,88067569,2023-11-24 16:16:56,2023-11-24 16:34:56,2023-11-24 16:33:56,On Time,440.23,Card,61497,7917
4,5427684290,83298567,2023-11-20 05:00:39,2023-11-20 05:17:39,2023-11-20 05:18:39,On Time,2526.68,Cash,84315,2741

In [12]:
ord_df['promised_delivery_time'] = pd.to_datetime(ord_df['promised_delivery_time'])
ord_df['actual_delivery_time'] = pd.to_datetime(ord_df['actual_delivery_time'])

In [13]:
ord_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   order_id                5000 non-null   int64
 1   customer_id             5000 non-null   int64
 2   order_date              5000 non-null   datetime64[us]
 3   promised_delivery_time  5000 non-null   datetime64[us]
 4   actual_delivery_time    5000 non-null   datetime64[us]
 5   delivery_status         5000 non-null   str
 6   order_total             5000 non-null   float64
 7   payment_method          5000 non-null   str
 8   delivery_partner_id     5000 non-null   int64
 9   store_id                5000 non-null   int64
dtypes: datetime64[us](3), float64(1), int64(4), str(2)
memory usage: 390.8 KB

In [14]:
prod_df['product_id'].nunique()

268

In [15]:
prod_df

,product_id,product_name,category,brand,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level
0,153019,Onions,Fruits & Vegetables,Aurora LLC,947.95,1263.93,25.0,3,13,88
1,11422,Potatoes,Fruits & Vegetables,Ramaswamy-Tata,127.16,169.55,25.0,3,20,65
2,669378,Potatoes,Fruits & Vegetables,Chadha and Sons,212.14,282.85,25.0,3,23,70
3,848226,Tomatoes,Fruits & Vegetables,Barad and Sons,209.59,279.45,25.0,3,10,51
4,890623,Onions,Fruits & Vegetables,"Sangha, Nagar and Varty",354.52,472.69,25.0,3,27,55
...,...,...,...,...,...,...,...,...,...,...
263,444361,Pain Reliever,Pharmacy,"Prakash, Bawa and Kale",822.63,1028.29,20.0,365,20,71
264,679284,Cough Syrup,Pharmacy,Pant LLC,877.89,1097.36,20.0,365,28,95
265,240179,Cough Syrup,Pharmacy,Ram-Suri,90.56,113.20,20.0,365,20,56
266,673058,Cough Syrup,Pharmacy,Balan-Madan,765.76,957.20,20.0,365,30,94
267,114414,Vitamins,Pharmacy,Kara-Golla,832.06,1040.07,20.0,365,26,66

In [16]:
prod_df[['product_id', 'product_name', 'category', 'brand', 'price', 'mrp',
       'margin_percentage', 'shelf_life_days', 'min_stock_level',
       'max_stock_level']].nunique()

product_id           268
product_name          51
category              11
brand                267
price                267
mrp                  268
margin_percentage      6
shelf_life_days        5
min_stock_level       21
max_stock_level       51
dtype: int64

In [17]:
ord_item_df['revenue'] = (
    ord_item_df['quantity'] *
    ord_item_df['unit_price']
)

In [18]:
ord_item_df

        order_id  product_id  quantity  unit_price  revenue
0     1961864118      642612         3      517.03  1551.09
1     1549769649      378676         1      881.42   881.42
2     9185164487      741341         2      923.84  1847.68
3     9644738826      561860         1      874.78   874.78
4     5427684290      602241         2      976.55  1953.10
...          ...         ...       ...         ...      ...
4995  1669690997      925482         3      475.04  1425.12
4996  8340761903      124290         2       39.65    79.30
4997  5936301790      491314         3      973.44  2920.32
4998  5710579377      319388         2      657.80  1315.60
4999  2494813730      136533         1      826.21   826.21

[5000 rows x 5 columns]

In [19]:
ord_item_df[['order_id', 'product_id', 'quantity', 'unit_price', 'revenue']].nunique()

order_id      5000
product_id     268
quantity         3
unit_price     267
revenue        799
dtype: int64

In [20]:
ord_item_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    5000 non-null   int64
 1   product_id  5000 non-null   int64
 2   quantity    5000 non-null   int64
 3   unit_price  5000 non-null   float64
 4   revenue     5000 non-null   float64
dtypes: float64(2), int64(3)
memory usage: 195.4 KB

In [21]:
print(ord_item_df.columns)

Index(['order_id', 'product_id', 'quantity', 'unit_price', 'revenue'], dtype='str')

In [22]:
ord_df['customer_id'].isin(cus_df['customer_id']).all()

np.True_

In [23]:
ord_item_df['order_id'].isin(ord_df['order_id']).all()

np.True_

In [24]:
ord_item_df['product_id'].isin(prod_df['product_id']).all()

np.True_

In [25]:
feedback_df = feedback_df[
    feedback_df['rating'].between(1,5)
]

In [26]:
inventory_df['date'] = pd.to_datetime(inventory_df['date'])
inventory_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 75172 entries, 0 to 75171
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_id      75172 non-null  int64
 1   date            75172 non-null  datetime64[us]
 2   stock_received  75172 non-null  int64
 3   damaged_stock   75172 non-null  int64
dtypes: datetime64[us](1), int64(3)
memory usage: 2.3 MB

C:\Users\Admin\AppData\Local\Temp\ipykernel_8868\3812079419.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  inventory_df['date'] = pd.to_datetime(inventory_df['date'])

In [27]:
order_revenue = (
    ord_item_df.groupby('order_id')['revenue']
    .sum()
    .reset_index()
)

In [28]:
cus_df.to_csv("Clean Data/customers_clean.csv", index=False)

ord_df.to_csv("Clean Data/orders_clean.csv", index=False)

ord_item_df.to_csv("Clean Data/order_items_clean.csv", index=False)

prod_df.to_csv("Clean Data/products_clean.csv", index=False)

feedback_df.to_csv("Clean Data/customer_feedback_clean.csv", index=False)

delivery_df.to_csv("Clean Data/delivery_performance_clean.csv", index=False)

inventory_df.to_csv("Clean Data/inventory_clean.csv", index=False)

inventory_new_df.to_csv("Clean Data/inventory_new_clean.csv", index=False)

marketing_df.to_csv("Clean Data/marketing_performance_clean.csv", index=False)

category_icon_df.to_csv("Clean Data/category_icon_clean.csv", index=False)

rating_icon_df.to_csv("Clean Data/rating_icon_clean.csv", index=False)